# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BasicFramework' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BasicFramework
  
  pod 'AFNetworking', '~> 3.2.1'
  pod 'SDWebImage', '~> 5.0.0-beta6'
  pod 'MJRefresh', '~> 3.1.16'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'JSONModel', '~> 1.8.0'
  pod 'Masonry', '~> 1.1.0'
  pod 'YYCache', '~> 1.0.4'
  
end
